services:
  server:
    build: ./server
    ports:
      - "8080:8080"
  
  client1:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true

  client2:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true

  client3:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true

  client4:
    build: ./client
    depends_on:
      - server
    stdin_open: true
    tty: true
